### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by VeniQs02** [VeniQs02/portfolio-web-app#1]
TODO:
- [x] responsiveness to smaller screens
- [x] the sidebar needs to move on top, if the screen is to small
- [x] picture galleries in projects
- [x] describing projects
- [x] sidebar buttons working

additional todos:
- [x] i18n - or at least polish and english
- [x] dark/light mode toggle 
- [x] pictures getting bigger when clicked
- [x] disable sidebar -> resize screen to less than 1400 -> centered section is no more centered - why?
- [x] flipping cards could be smoother
- [x] fix bugs that appear in the console
